# Generated by Django 5.0.6 on 2024-06-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadPrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrimask',
            name='headMRI',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mask', to='threadPrediction.headmri'),
        ),
    ]
