# Generated by Django 5.0.6 on 2024-06-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadPrediction', '0002_alter_mrimask_headmri'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='Verdict',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
