# Generated by Django 5.0.6 on 2024-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadPrediction', '0003_research_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='Verdict',
            field=models.BooleanField(null=True),
        ),
    ]
